server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/docassist
    username: docassist
    password: docassist
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: auth_db
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  jackson:
    default-property-inclusion: non_null

app:
  jwt:
    secret: dGhpcyBpcyBhIHZlcnkgbG9uZyBzZWNyZXQga2V5IGZvciBkb2Nhc3Npc3QgYXBwbGljYXRpb24gand0IHNpZ25pbmc=
    expiration-ms: 86400000
    refresh-expiration-ms: 604800000

springdoc:
  api-docs:
    path: /api/auth/v3/api-docs
  swagger-ui:
    path: /api/auth/swagger-ui.html
